#include "Compiler.h"
#include "ErrorHandler.h"
#include <stdlib.h>
#include <assert.h>

/* ----------------------------------------------------------------
 * Test / debug helpers
 * These are not called in the normal pipeline; uncomment the calls
 * inside startCompiler() to activate them during development.
 * ---------------------------------------------------------------- */

void testLexer(Compiler* compiler) {
    Token* token;
    while ((token = nextToken(compiler->lexer))->type != TOKEN_EOF) {
        if (token->type != TOKEN_NEWLINE)
            printf("Token: %s -- %d\n", token->lexeme, token->type);
        free(token->lexeme);
        free(token);
    }
    free(token->lexeme);
    free(token);
}

void testParser(Compiler* compiler) {
    Parser* parser = compiler->parser;
    Token* currentToken = NULL;
    int stage, next;

    stage = next = 1;

    printf("--- Starting Parser Test: ---\n\n");
    do {
        if (next)
            currentToken = nextToken(compiler->lexer);

        while (currentToken->type == TOKEN_NEWLINE) {
            free(currentToken->lexeme);
            free(currentToken);
            currentToken = nextToken(compiler->lexer);
        }

        printf("%03d Stack: ", stage++);
        printStack(parser->stack);

    } while (!nextAction(parser, compiler->lexer, &currentToken, &next));

    if (!errorCount) {
        printf(GREEN "--- Syntax Analysis Complete: No errors found ---\n" RESET);
        printCST(parser->cst);
    } else {
        printf(RED "--- Syntax Analysis Complete: %d errors found ---\n" RESET,
               errorCount);
        freeCompiler(compiler);
        exit(EXIT_FAILURE);
    }
}

/* ----------------------------------------------------------------
 * Internal pipeline stages
 * ---------------------------------------------------------------- */

/* Run the LR parser over the full token stream, building the CST */
static void runParser(Compiler* compiler) {
    Parser* parser = compiler->parser;
    Token* currentToken = NULL;
    int next = 1;

    do {
        if (next)
            currentToken = nextToken(compiler->lexer);

        /* Skip newline tokens — they are only meaningful to the lexer */
        while (currentToken->type == TOKEN_NEWLINE) {
            free(currentToken->lexeme);
            free(currentToken);
            currentToken = nextToken(compiler->lexer);
        }

    } while (!nextAction(parser, compiler->lexer, &currentToken, &next));
}

/* Walk the finished CST and check types and declarations */
static void runSemantic(Compiler* compiler) {
    if (compiler->parser && compiler->parser->cst)
        analyzeCST(compiler->analyzer, compiler->parser->cst);
    else
        reportError(ERROR_INTERNAL, 0, "No CST generated by the parser");
}

/* ----------------------------------------------------------------
 * Public API
 * ---------------------------------------------------------------- */

Compiler* initCompiler(const char* filePath) {
    Compiler* compiler = (Compiler*)malloc(sizeof(Compiler));

    if (!compiler)
        reportError(ERROR_INTERNAL, 0, "Failed to allocate memory for compiler");

    assert(compiler);

    compiler->lexer = initLexer(filePath);
    compiler->parser = initParser();
    compiler->analyzer = initSemanticAnalyzer();
    compiler->generator = initCodeGenerator(filePath);

    /* Register with the error handler so reportError() can clean up on exit */
    setCurrentCompiler(compiler);

    return compiler;
}

void startCompiler(Compiler* compiler) {
    /*
       testLexer(compiler);
       testParser(compiler);
    */

    runParser(compiler);
    runSemantic(compiler);

    if (!errorCount) {
        printf(GREEN "--- Compilation Complete: No errors found ---\n\n" RESET);
        generateAndLinkCode(compiler->generator, compiler->parser->cst);
    } else {
        printf(RED "--- Compilation Complete: %d errors found ---\n\n" RESET,
               errorCount);
    }
}

void freeCompiler(Compiler* compiler) {
    if (!compiler) return;

    if (compiler->lexer) freeLexer(compiler->lexer);
    if (compiler->parser) freeParser(compiler->parser);
    if (compiler->analyzer) freeSemanticAnalyzer(compiler->analyzer);
    if (compiler->generator) freeCodeGenerator(compiler->generator);

    free(compiler);
}